### PR TITLE
Features

### PR DESCRIPTION
**Pull request by carlos-ssh**
TSE's Review.

- Create Test for all enumerables
- Installed Rspec
- Tested and Lint code.

Happy Coding

Carlos Robles

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work! 🖥️ 👀 ✨ 

- The tests seem fairly thorough.

## However, some changes are still required... 🧰 🔨 🔧 

I noticed that for some methods such as `#my_each_with_index` and `#my_select`, you only test for positive cases where the input and output are expected correct values.

Let's implement some [defensive programming](https://en.wikipedia.org/wiki/Defensive_programming) by implementing tests that generate errors or undesired output on purpose, to test those results as well. Remember that it's good practice to prepare your tests for the positive, as well as the negative, unexpected cases.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by carlos-ssh** [comment]
Work on negative cases in some tests and implement defensive programming on these tests.

Greetings!

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team    
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [ ] Let's activate linter checks for this project
- [ ] You have some failed tests, lets work on it.
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by carlos-ssh** [comment]
Fixed requested issues: 
- Let's activate linter checks for this project
- You have some failed tests, let's work on it.

Greetings.

**Review by elmejdki — APPROVED** [review]
# status: approved :heavy_check_mark: 
## Well done Carlos, your project is approved

now you can merge and go tackle the next project your project is approved.

## Happy Coding :tophat:

**Pull request merged**
